{
  "uid" : "38704c7dd6ed4b9e",
  "name" : "test_broken",
  "fullName" : "test_alluredemo1#test_broken",
  "historyId" : "62e3d0efc8226834b589024da8762ee8",
  "time" : {
    "start" : 1588912714628,
    "stop" : 1588912714629,
    "duration" : 1
  },
  "status" : "broken",
  "statusMessage" : "Exception: oops",
  "statusTrace" : "def test_broken():\n>       raise Exception('oops')\nE       Exception: oops\n\ntest_alluredemo1.py:19: Exception",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "suite",
    "value" : "test_alluredemo1"
  }, {
    "name" : "host",
    "value" : "PC-20201204TOIX"
  }, {
    "name" : "thread",
    "value" : "8088-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test_alluredemo1"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "38704c7dd6ed4b9e.json",
  "parameterValues" : [ ]
}